#define     CMD_TEST                     0
#define     CMD_LOGIN                    1
#define     CMD_PLACE_POT                2
#define     CMD_HIDE_POT                 3
#define     CMD_UPGRADE_POT              4
#define     CMD_PLANT                    5
#define     CMD_HARVEST                  6
#define     CMD_OPEN_NEW_FLOOR           7
#define     CMD_UPGRADE_STOCK            8
#define     CMD_START_MACHINE            9
#define     CMD_CREATE_PRODUCT           10
#define     CMD_MOVE_POT                 11
#define     CMD_UPGRADE_MACHINE          12
#define     CMD_REPAIR_MACHINE           13
#define     CMD_PRODUCT_COMPLETED        14
#define     CMD_UPGRADE_PRODUCT_SLOT	  15
#define     CMD_MOVE_MACHINE_PRODUCT	  16
#define     CMD_PRODUCT_SKIP_TIME		 17
#define     CMD_CREATE_ORDER			 18
#define     CMD_CATCH_BUG				 19
#define     CMD_READY_MACHINE			 20
#define     CMD_SKIP_MACHINE_UNLOCK_TIME  21
#define     CMD_BUY_ITEM				    22
#define     CMD_PLANT_INSTANT_GROW_UP	 23
#define     CMD_ORDER_DILIVERY            24
#define     CMD_ORDER_SKIP              25
#define     CMD_ORDER_WAIT_SKIP         26
#define     CMD_COMPLETE_ORDER    27
#define     CMD_BUY_MATERIAL_UPRADE_POT    46
// for testing only, will remove later
#define     CMD_REQUEST_FLOOR_INFO       100
#define     CMD_KEEP_ALIVE               101
#define     CMD_REQUEST_STOCK_INFO       102
#define     CMD_REQUEST_USER_INFO        103
#define     CMD_ORDER_DILIVERY            24
