
// ------------------------------------- SHEET_INDEX -------------------------------
#define SHEET_USER						0
#define SHEET_USER_LEVEL				SHEET_USER + 1
#define SHEET_SEED						SHEET_USER_LEVEL + 1
#define SHEET_POT						SHEET_SEED + 1
#define SHEET_PEST						SHEET_POT + 1
#define SHEET_PEARL						SHEET_PEST + 1
#define SHEET_STOCK						SHEET_PEARL + 1
#define SHEET_STOCK_UPGRADE				SHEET_STOCK + 1
#define SHEET_MACHINE					SHEET_STOCK_UPGRADE + 1
#define SHEET_MACHINE_UNLOCK			SHEET_MACHINE + 1
#define SHEET_MACHINE_UNLOCK_PROD_SLOT	SHEET_MACHINE_UNLOCK + 1
#define SHEET_PRODUCT					SHEET_MACHINE_UNLOCK_PROD_SLOT + 1
#define SHEET_MATERIAL					SHEET_PRODUCT + 1
#define SHEET_FLOOR_UNLOCK				SHEET_MATERIAL + 1
#define SHEET_IBSHOP_ITEM				SHEET_FLOOR_UNLOCK + 1
