#ifndef DEFINE_NPC_ORDER_H_INCLUDED
#define DEFINE_NPC_ORDER_H_INCLUDED

#define     IT_ORDER_NPC_TXT    TXT_NPC_0
#define     IT_ORDER_NPC        NPC_ORDER_ANIM_NPC_01

#endif // DEFINE_ITEM_H_INCLUDED
