



#define SHEET_USER 					 0
#define SHEET_USER_LEVEL 					 SHEET_USER + 1
#define SHEET_SEED 					 SHEET_USER_LEVEL + 1
#define SHEET_POT 					 SHEET_SEED + 1
#define SHEET_PEST 					 SHEET_POT + 1
#define SHEET_STOCK 					 SHEET_PEST + 1
#define SHEET_STOCK_UPGRADE 					 SHEET_STOCK + 1
#define SHEET_MACHINE 					 SHEET_STOCK_UPGRADE + 1
#define SHEET_MACHINE_UNLOCK 					 SHEET_MACHINE + 1
#define SHEET_MACHINE_UNLOCK_PROD_SLOT 					 SHEET_MACHINE_UNLOCK + 1
#define SHEET_PRODUCT 					 SHEET_MACHINE_UNLOCK_PROD_SLOT + 1
#define SHEET_MATERIAL 					 SHEET_PRODUCT + 1
#define SHEET_FLOOR_UNLOCK 					 SHEET_MATERIAL + 1
#define SHEET_IBSHOP_ITEM 					 SHEET_FLOOR_UNLOCK + 1
#define SHEET_PRIVATE_SHOP 					 SHEET_IBSHOP_ITEM + 1
#define SHEET_ACHIEVEMENT 					 SHEET_PRIVATE_SHOP + 1
#define SHEET_DIAMOND_SKIP_TIME 					 SHEET_ACHIEVEMENT + 1
#define SHEET_ITEM_DROP 					 SHEET_DIAMOND_SKIP_TIME + 1
#define SHEET_GOLD_XP_COEFFICIENT 					 SHEET_ITEM_DROP + 1
#define SHEET_PAYMENT 					 SHEET_GOLD_XP_COEFFICIENT + 1
#define SHEET_DAILY_ORDER 					 SHEET_PAYMENT + 1
#define SHEET_TUTORIAL 					 SHEET_DAILY_ORDER + 1
#define SHEET_VERSION 					 SHEET_TUTORIAL + 1
#define SHEET_CONSTANT 					 SHEET_VERSION + 1
#define SHEET_MAX 					 SHEET_CONSTANT + 1


#define USER_GOLD 					 0
#define USER_DIAMOND 					 USER_GOLD + 1
#define USER_REPUTAION 					 USER_DIAMOND + 1
#define USER_FLOOR 					 USER_REPUTAION + 1
#define USER_PROPERTY_MAX 					 USER_FLOOR + 1


#define USER_LEVEL 					 0
#define USER_EXP_LVL 					 USER_LEVEL + 1
#define USER_SEED_ID_UNLOCK 					 USER_EXP_LVL + 1
#define USER_POT_ID_UNLOCK 					 USER_SEED_ID_UNLOCK + 1
#define USER_PROD_ID_UNLOCK 					 USER_POT_ID_UNLOCK + 1
#define USER_FLOOR_UNLOCK 					 USER_PROD_ID_UNLOCK + 1
#define USER_MACHINE_UNLOCK 					 USER_FLOOR_UNLOCK + 1
#define USER_ORDER_SLOT_UNLOCK 					 USER_MACHINE_UNLOCK + 1
#define USER_ITEM_PER_ORDER 					 USER_ORDER_SLOT_UNLOCK + 1
#define USER_ITEM_MAX 					 USER_ITEM_PER_ORDER + 1
#define USER_REWARD_GOLD 					 USER_ITEM_MAX + 1
#define USER_REWARD_REPUTATION 					 USER_REWARD_GOLD + 1
#define USER_REWARD_DIAMOND 					 USER_REWARD_REPUTATION + 1
#define USER_REWARD_ITEM 					 USER_REWARD_DIAMOND + 1
#define USER_ITEM_PER_ORDER_BUG_PEARL 					 USER_REWARD_ITEM + 1
#define USER_ITEM_MAX_ORDER_BUG_PEARL 					 USER_ITEM_PER_ORDER_BUG_PEARL + 1
#define USER_ITEM_MIN_ORDER_DAILY 					 USER_ITEM_MAX_ORDER_BUG_PEARL + 1
#define USER_ITEM_MAX_ORDER_DAILY 					 USER_ITEM_MIN_ORDER_DAILY + 1
#define USER_NEW_ORDER_WAIT_TIME 					 USER_ITEM_MAX_ORDER_DAILY + 1
#define USER_DAILY_ORDER_DIAMOND_RATIO 					 USER_NEW_ORDER_WAIT_TIME + 1
#define USER_DO_LETTER_1 					 USER_DAILY_ORDER_DIAMOND_RATIO + 1
#define USER_DO_LETTER_2 					 USER_DO_LETTER_1 + 1
#define USER_DO_LETTER_3 					 USER_DO_LETTER_2 + 1
#define USER_DO_LETTER_4 					 USER_DO_LETTER_3 + 1
#define USER_DO_LETTER_5 					 USER_DO_LETTER_4 + 1
#define USER_DO_LETTER_6 					 USER_DO_LETTER_5 + 1
#define USER_NPC_MACHINE_CORRUPT 					 USER_DO_LETTER_6 + 1
#define USER_UNLOCK_PROPERTY_MAX 					 USER_NPC_MACHINE_CORRUPT + 1


#define SEED_ID 					 0
#define SEED_NAME 					 SEED_ID + 1
#define SEED_GROW_TIME 					 SEED_NAME + 1
#define SEED_HARVEST_EXP 					 SEED_GROW_TIME + 1
#define SEED_ITEM_RECEIVE_RATIO 					 SEED_HARVEST_EXP + 1
#define SEED_DIAMOND_SKIP_TIME 					 SEED_ITEM_RECEIVE_RATIO + 1
#define SEED_DIAMOND_BUY 					 SEED_DIAMOND_SKIP_TIME + 1
#define SEED_GOLD_BASIC 					 SEED_DIAMOND_BUY + 1
#define SEED_EXP_BASIC 					 SEED_GOLD_BASIC + 1
#define SEED_GOLD_SELL_DEFAULT 					 SEED_EXP_BASIC + 1
#define SEED_GOLD_SELL_MIN 					 SEED_GOLD_SELL_DEFAULT + 1
#define SEED_GOLD_SELL_MAX 					 SEED_GOLD_SELL_MIN + 1
#define SEED_BUG_ID 					 SEED_GOLD_SELL_MAX + 1
#define SEED_BUG_APPEAR_RATIO 					 SEED_BUG_ID + 1
#define SEED_LEVEL_UNLOCK 					 SEED_BUG_APPEAR_RATIO + 1
#define SEED_SEED_TIME 					 SEED_LEVEL_UNLOCK + 1
#define SEED_GOLD_BASIC_DO 					 SEED_SEED_TIME + 1
#define SEED_EXP_BASIC_DO 					 SEED_GOLD_BASIC_DO + 1
#define SEED_PROPERTY_MAX 					 SEED_EXP_BASIC_DO + 1


#define POT_ID 					 0
#define POT_NAME 					 POT_ID + 1
#define POT_EXP_INCREASE 					 POT_NAME + 1
#define POT_TIME_DECREASE 					 POT_EXP_INCREASE + 1
#define POT_GOLD_UPGRADE 					 POT_TIME_DECREASE + 1
#define POT_PEARL_ID_NUM 					 POT_GOLD_UPGRADE + 1
#define POT_UPGRADE_RATIO 					 POT_PEARL_ID_NUM + 1
#define POT_GOLD_DEFAULT 					 POT_UPGRADE_RATIO + 1
#define POT_GOLD_MIN 					 POT_GOLD_DEFAULT + 1
#define POT_GOLD_MAX 					 POT_GOLD_MIN + 1
#define POT_BUG_APPEAR_RATIO 					 POT_GOLD_MAX + 1
#define POT_LEVEL_UNLOCK 					 POT_BUG_APPEAR_RATIO + 1
#define POT_BLESSING_RATIO 					 POT_LEVEL_UNLOCK + 1
#define POT_BAD_LUCK_RATIO 					 POT_BLESSING_RATIO + 1
#define POT_COMBO_EXP_BONUS 					 POT_BAD_LUCK_RATIO + 1
#define POT_COMBO_TIME_BONUS 					 POT_COMBO_EXP_BONUS + 1
#define POT_COMBO_BUG_BONUS 					 POT_COMBO_TIME_BONUS + 1
#define POT_PROPERTY_MAX 					 POT_COMBO_BUG_BONUS + 1


#define PEST_ID 					 0
#define PEST_NAME 					 PEST_ID + 1
#define PEST_DIAMOND_BUY 					 PEST_NAME + 1
#define PEST_GOLD_BASIC 					 PEST_DIAMOND_BUY + 1
#define PEST_EXP_BASIC 					 PEST_GOLD_BASIC + 1
#define PEST_GOLD_DEFAULT 					 PEST_EXP_BASIC + 1
#define PEST_GOLD_MIN 					 PEST_GOLD_DEFAULT + 1
#define PEST_GOLD_MAX 					 PEST_GOLD_MIN + 1
#define PEST_PROPERTY_MAX 					 PEST_GOLD_MAX + 1


#define STOCK_ID 					 0
#define STOCK_NAME 					 STOCK_ID + 1
#define STOCK_CAPACITY_MAX 					 STOCK_NAME + 1
#define STOCK_CAPACITY_ADD 					 STOCK_CAPACITY_MAX + 1
#define STOCK_CAPACITY_PLUS 					 STOCK_CAPACITY_ADD + 1
#define STOCK_VIP_PLUS 					 STOCK_CAPACITY_PLUS + 1
#define STOCK_PROPERTY_MAX 					 STOCK_VIP_PLUS + 1


#define STOCK_1 					 0
#define STOCK_2 					 STOCK_1 + 1
#define STOCK_3 					 STOCK_2 + 1
#define STOCK_UPGRADE_PROPERTY_MAX 					 STOCK_3 + 1


#define MACHINE_FLOOR 					 0
#define MACHINE_ID 					 MACHINE_FLOOR + 1
#define MACHINE_NAME 					 MACHINE_ID + 1
#define MACHINE_LEVEL_UNLOCK 					 MACHINE_NAME + 1
#define MACHINE_GOLD_START 					 MACHINE_LEVEL_UNLOCK + 1
#define MACHINE_TIME_START 					 MACHINE_GOLD_START + 1
#define MACHINE_PRODUCT_ID 					 MACHINE_TIME_START + 1
#define MACHINE_DURABILITY 					 MACHINE_PRODUCT_ID + 1
#define MACHINE_PROPERTY_MAX 					 MACHINE_DURABILITY + 1


#define MACHINE_LEVEL1 					 0
#define MACHINE_LEVEL2 					 MACHINE_LEVEL1 + 1
#define MACHINE_LEVEL3 					 MACHINE_LEVEL2 + 1
#define MACHINE_LEVEL4 					 MACHINE_LEVEL3 + 1
#define MACHINE_LEVEL5 					 MACHINE_LEVEL4 + 1
#define MACHINE_LEVEL6 					 MACHINE_LEVEL5 + 1
#define MACHINE_LEVEL7 					 MACHINE_LEVEL6 + 1
#define MACHINE_LEVEL8 					 MACHINE_LEVEL7 + 1
#define MACHINE_LEVEL_MAX 					 MACHINE_LEVEL8 + 1

#define MACHINE_ACTIVE_TIME 					 0
#define MACHINE_GOLD_UNLOCK 					 MACHINE_ACTIVE_TIME + 1
#define MACHINE_UPGRADE_RATIO 					 MACHINE_GOLD_UNLOCK + 1
#define MACHINE_EXP_BONUS 					 MACHINE_UPGRADE_RATIO + 1
#define MACHINE_REDUCE_TIME 					 MACHINE_EXP_BONUS + 1
#define MACHINE_EXP_ORDER 					 MACHINE_REDUCE_TIME + 1
#define MACHINE_GOLD_ORDER 					 MACHINE_EXP_ORDER + 1
#define MACHINE_GOLD_MAINTAIN 					 MACHINE_GOLD_ORDER + 1
#define MACHINE_UNLOCK_PROPERTY_MAX 					 MACHINE_GOLD_MAINTAIN + 1


#define MACHINE_SLOT_0 					 0
#define MACHINE_SLOT_1 					 MACHINE_SLOT_0 + 1
#define MACHINE_SLOT_2 					 MACHINE_SLOT_1 + 1
#define MACHINE_SLOT_3 					 MACHINE_SLOT_2 + 1
#define MACHINE_SLOT_4 					 MACHINE_SLOT_3 + 1
#define MACHINE_SLOT_5 					 MACHINE_SLOT_4 + 1
#define MACHINE_SLOT_6 					 MACHINE_SLOT_5 + 1
#define MACHINE_SLOT_7 					 MACHINE_SLOT_6 + 1
#define MACHINE_SLOT_8 					 MACHINE_SLOT_7 + 1
#define MACHINE_SLOT_9 					 MACHINE_SLOT_8 + 1
#define MACHINE_SLOT_10 					 MACHINE_SLOT_9 + 1
#define MACHINE_SLOT_11 					 MACHINE_SLOT_10 + 1
#define MACHINE_SLOT_12 					 MACHINE_SLOT_11 + 1
#define MACHINE_SLOT_13 					 MACHINE_SLOT_12 + 1
#define MACHINE_SLOT_14 					 MACHINE_SLOT_13 + 1
#define MACHINE_SLOT_15 					 MACHINE_SLOT_14 + 1
#define MACHINE_SLOT_16 					 MACHINE_SLOT_15 + 1
#define MACHINE_SLOT_PROPERTY_MAX 					 MACHINE_SLOT_16 + 1


#define PRODUCT_ID 					 0
#define PRODUCT_NAME 					 PRODUCT_ID + 1
#define PRODUCT_LEVEL_UNLOCK 					 PRODUCT_NAME + 1
#define PRODUCT_MACHINE_ID 					 PRODUCT_LEVEL_UNLOCK + 1
#define PRODUCT_ITEMS_TYPE_ID_NUM 					 PRODUCT_MACHINE_ID + 1
#define PRODUCT_PRODUCTION_TIME 					 PRODUCT_ITEMS_TYPE_ID_NUM + 1
#define PRODUCT_EXP_RECEIVE 					 PRODUCT_PRODUCTION_TIME + 1
#define PRODUCT_DIAMOND_BUY 					 PRODUCT_EXP_RECEIVE + 1
#define PRODUCT_GOLD_BASIC 					 PRODUCT_DIAMOND_BUY + 1
#define PRODUCT_EXP_BASIC 					 PRODUCT_GOLD_BASIC + 1
#define PRODUCT_GOLD_DEFAULT 					 PRODUCT_EXP_BASIC + 1
#define PRODUCT_GOLD_MIN 					 PRODUCT_GOLD_DEFAULT + 1
#define PRODUCT_GOLD_MAX 					 PRODUCT_GOLD_MIN + 1
#define PRODUCT_PROPERTY_MAX 					 PRODUCT_GOLD_MAX + 1


#define MATERIAL_ID 					 0
#define MATERIAL_NAME 					 MATERIAL_ID + 1
#define MATERIAL_DIAMOND_BUY 					 MATERIAL_NAME + 1
#define MATERIAL_GOLD_DEFAULT 					 MATERIAL_DIAMOND_BUY + 1
#define MATERIAL_GOLD_MIN 					 MATERIAL_GOLD_DEFAULT + 1
#define MATERIAL_GOLD_MAX 					 MATERIAL_GOLD_MIN + 1
#define MATERIAL_4_LEAF_LUCKY_PERCENT 					 MATERIAL_GOLD_MAX + 1
#define MATERIAL_PROPERTY_MAX 					 MATERIAL_4_LEAF_LUCKY_PERCENT + 1


#define FLOOR_UNLOCK_ID 					 0
#define FLOOR_UNLOCK_USER_LEVEL 					 FLOOR_UNLOCK_ID + 1
#define FLOOR_UNLOCK_GOLD 					 FLOOR_UNLOCK_USER_LEVEL + 1
#define FLOOR_UNLOCK_REPUTATION 					 FLOOR_UNLOCK_GOLD + 1
#define FLOOR_UNLOCK_MATERIAL_ID_NUM 					 FLOOR_UNLOCK_REPUTATION + 1
#define FLOOR_UNLOCK_PROPERTY_MAX 					 FLOOR_UNLOCK_MATERIAL_ID_NUM + 1


#define IBSHOP_ID 					 0
#define IBSHOP_NAME 					 IBSHOP_ID + 1
#define IBSHOP_DESCRIPTION 					 IBSHOP_NAME + 1
#define IBSHOP_TYPE 					 IBSHOP_DESCRIPTION + 1
#define IBSHOP_ITEM_NAME 					 IBSHOP_TYPE + 1
#define IBSHOP_ITEM_QUANTITY 					 IBSHOP_ITEM_NAME + 1
#define IBSHOP_IS_ACTIVE 					 IBSHOP_ITEM_QUANTITY + 1
#define IBSHOP_IS_NEW 					 IBSHOP_IS_ACTIVE + 1
#define IBSHOP_IS_HOT 					 IBSHOP_IS_NEW + 1
#define IBSHOP_IS_SALE_OFF 					 IBSHOP_IS_HOT + 1
#define IBSHOP_SALE_OFF_PERCENT 					 IBSHOP_IS_SALE_OFF + 1
#define IBSHOP_HAS_PROMOTION 					 IBSHOP_SALE_OFF_PERCENT + 1
#define IBSHOP_GIFT_WHEN_BUY 					 IBSHOP_HAS_PROMOTION + 1
#define IBSHOP_REQUIRED_GOLD 					 IBSHOP_GIFT_WHEN_BUY + 1
#define IBSHOP_REQUIRED_DIAMOND 					 IBSHOP_REQUIRED_GOLD + 1
#define IBSHOP_REQUIRED_REPUTATION 					 IBSHOP_REQUIRED_DIAMOND + 1
#define IBSHOP_HAS_TIME_LIMIT 					 IBSHOP_REQUIRED_REPUTATION + 1
#define IBSHOP_SALE_DURATION 					 IBSHOP_HAS_TIME_LIMIT + 1
#define IBSHOP_HAS_SALE_LIMIT 					 IBSHOP_SALE_DURATION + 1
#define IBSHOP_SALE_TOTAL_QUANTITY 					 IBSHOP_HAS_SALE_LIMIT + 1
#define IBSHOP_UNLOCK_LEVEL 					 IBSHOP_SALE_TOTAL_QUANTITY + 1
#define IBSHOP_PROPERTY_MAX 					 IBSHOP_UNLOCK_LEVEL + 1


#define IBS_TAB_DIAMOND 					 0
#define IBS_TAB_GOLD 					 1
#define IBS_TAB_POT 					 2
#define IBS_TAB_DECOR 					 3
#define IBS_TAB_UPGRADE 					 4
#define IBS_TAB_MACHINE 					 5
#define IBS_TAB_MISCELLANEOUS 					 6
#define IBS_TAB_PLANT 					 7
#define IBS_TAB_MAX 					 8


#define PS_SHOP_SLOT_ID 					 0
#define PS_SHOP_REQUIRED_FRIEND 					 PS_SHOP_SLOT_ID + 1
#define PS_SHOP_REQUIRED_DIAMOND 					 PS_SHOP_REQUIRED_FRIEND + 1
#define PS_SHOP_REQUIRED_DIAMOND_CANCEL 					 PS_SHOP_REQUIRED_DIAMOND + 1
#define PS_SHOP_PROPERTY_MAX 					 PS_SHOP_REQUIRED_DIAMOND_CANCEL + 1


#define ACHIEVEMENT_ID 					 0
#define ACHIEVEMENT_NAME 					 ACHIEVEMENT_ID + 1
#define ACHIEVEMENT_TASK_LEVEL_1 					 ACHIEVEMENT_NAME + 1
#define ACHIEVEMENT_TASK_LEVEL_2 					 ACHIEVEMENT_TASK_LEVEL_1 + 1
#define ACHIEVEMENT_TASK_LEVEL_3 					 ACHIEVEMENT_TASK_LEVEL_2 + 1
#define ACHIEVEMENT_TASK_LEVEL_MAX 					 ACHIEVEMENT_TASK_LEVEL_3 + 1
#define ACHIEVEMENT_PROPERTY_MAX 					 ACHIEVEMENT_TASK_LEVEL_MAX + 1


#define ACHIEVEMENT_0 					 0
#define ACHIEVEMENT_1 					 ACHIEVEMENT_0 + 1
#define ACHIEVEMENT_2 					 ACHIEVEMENT_1 + 1
#define ACHIEVEMENT_3 					 ACHIEVEMENT_2 + 1
#define ACHIEVEMENT_4 					 ACHIEVEMENT_3 + 1
#define ACHIEVEMENT_5 					 ACHIEVEMENT_4 + 1
#define ACHIEVEMENT_6 					 ACHIEVEMENT_5 + 1
#define ACHIEVEMENT_7 					 ACHIEVEMENT_6 + 1
#define ACHIEVEMENT_8 					 ACHIEVEMENT_7 + 1
#define ACHIEVEMENT_9 					 ACHIEVEMENT_8 + 1
#define ACHIEVEMENT_10 					 ACHIEVEMENT_9 + 1
#define ACHIEVEMENT_11 					 ACHIEVEMENT_10 + 1
#define ACHIEVEMENT_12 					 ACHIEVEMENT_11 + 1
#define ACHIEVEMENT_13 					 ACHIEVEMENT_12 + 1
#define ACHIEVEMENT_14 					 ACHIEVEMENT_13 + 1
#define ACHIEVEMENT_15 					 ACHIEVEMENT_14 + 1
#define ACHIEVEMENT_16 					 ACHIEVEMENT_15 + 1
#define ACHIEVEMENT_17 					 ACHIEVEMENT_16 + 1
#define ACHIEVEMENT_18 					 ACHIEVEMENT_17 + 1
#define ACHIEVEMENT_19 					 ACHIEVEMENT_18 + 1
#define ACHIEVEMENT_20 					 ACHIEVEMENT_19 + 1
#define ACHIEVEMENT_21 					 ACHIEVEMENT_20 + 1
#define ACHIEVEMENT_22 					 ACHIEVEMENT_21 + 1
#define ACHIEVEMENT_23 					 ACHIEVEMENT_22 + 1
#define ACHIEVEMENT_24 					 ACHIEVEMENT_23 + 1
#define ACHIEVEMENT_25 					 ACHIEVEMENT_24 + 1
#define ACHIEVEMENT_26 					 ACHIEVEMENT_25 + 1
#define ACHIEVEMENT_27 					 ACHIEVEMENT_26 + 1
#define ACHIEVEMENT_28 					 ACHIEVEMENT_27 + 1
#define ACHIEVEMENT_29 					 ACHIEVEMENT_28 + 1


#define DIAMOND_SKIP_TIME_PLANT_TIME_RANGE 					 0
#define DIAMOND_SKIP_TIME_PLANT_RATIO 					 DIAMOND_SKIP_TIME_PLANT_TIME_RANGE + 1
#define DIAMOND_SKIP_TIME_PLANT_DIAMOND_DEFAULT 					 DIAMOND_SKIP_TIME_PLANT_RATIO + 1
#define DIAMOND_SKIP_TIME_PRODUCT_TIME_RANGE 					 DIAMOND_SKIP_TIME_PLANT_DIAMOND_DEFAULT + 1
#define DIAMOND_SKIP_TIME_PRODUCT_RATIO 					 DIAMOND_SKIP_TIME_PRODUCT_TIME_RANGE + 1
#define DIAMOND_SKIP_TIME_PRODUCT_DIAMOND_DEFAULT 					 DIAMOND_SKIP_TIME_PRODUCT_RATIO + 1
#define DIAMOND_SKIP_TIME_MACHINE_TIME_RANGE 					 DIAMOND_SKIP_TIME_PRODUCT_DIAMOND_DEFAULT + 1
#define DIAMOND_SKIP_TIME_MACHINE_RATIO 					 DIAMOND_SKIP_TIME_MACHINE_TIME_RANGE + 1
#define DIAMOND_SKIP_TIME_MACHINE_DIAMOND_DEFAULT 					 DIAMOND_SKIP_TIME_MACHINE_RATIO + 1
#define DIAMOND_SKIP_TIME_PROPERTY_MAX 					 DIAMOND_SKIP_TIME_MACHINE_DIAMOND_DEFAULT + 1

#define DIAMOND_SKIP_TIME_PLANT 					 0
#define DIAMOND_SKIP_TIME_PRODUCT 					 DIAMOND_SKIP_TIME_PLANT + 1
#define DIAMOND_SKIP_TIME_MACHINE 					 DIAMOND_SKIP_TIME_PRODUCT + 1


#define DROP_INDEX 					 0
#define DROP_LEVEL 					 0
#define DROP_ITEM_GACH 					 1
#define DROP_ITEM_SONDO 					 2
#define DROP_ITEM_GO 					 3
#define DROP_ITEM_DA 					 4
#define DROP_ITEM_SONVANG 					 5
#define DROP_ITEM_DINH 					 6
#define DROP_ITEM_NGOI 					 7
#define DROP_ITEM_SONDEN 					 8
#define DROP_ITEM_SAT 					 9
#define DROP_ITEM_VOT 					 10
#define DROP_ITEM_NUOCTHAN 					 11
#define DROP_ITEM_PROPERTY_MAX 					 DROP_ITEM_NUOCTHAN + 1


#define GOLD_XP_COEFFICIENT_RATE 					 0
#define GOLD_XP_COEFFICIENT_RATE_RANGE 					 GOLD_XP_COEFFICIENT_RATE + 1
#define GOLD_XP_COEFFICIENT_MIN 					 GOLD_XP_COEFFICIENT_RATE_RANGE + 1
#define GOLD_XP_COEFFICIENT_MAX 					 GOLD_XP_COEFFICIENT_MIN + 1
#define GOLD_XP_COEFFICIENT_PROPERTY_MAX 					 GOLD_XP_COEFFICIENT_MAX + 1


#define PAYMENT_PACK_ID 					 0
#define PAYMENT_PACK_NAME 					 1
#define PAYMENT_PACK_DESCRIPTION 					 2
#define PAYMENT_TYPE 					 3
#define PAYMENT_GROSS_AMOUNT 					 4
#define PAYMENT_SMS_STRUCTURE 					 5
#define PAYMENT_SMS_ADDRESS 					 6
#define PAYMENT_IS_ACTIVE 					 7
#define PAYMENT_IS_NEW 					 8
#define PAYMENT_IS_HOT 					 9
#define PAYMENT_HAS_PROMOTION 					 10
#define PAYMENT_PROMOTION_PERCENT 					 11
#define PAYMENT_DIAMOND_RECEIVE 					 12
#define PAYMENT_PROPERTY_MAX 					 13

#define PAYMENT_CARD_ZING 					 0
#define PAYMENT_CARD_VNP 					 1
#define PAYMENT_CARD_VMS 					 2
#define PAYMENT_CARD_VTT 					 3


#define DAILY_ORDER_INDEX 					 0
#define DAILY_ORDER_GOLD_PER_DIAMOND 					 DAILY_ORDER_INDEX + 1
#define DAILY_ORDER_PROPERTY_MAX 					 DAILY_ORDER_GOLD_PER_DIAMOND + 1


#define TUTORIAL_ID 					 0
#define TUTORIAL_EXP 					 TUTORIAL_ID + 1

#define TUTORIAL_SLIDE_TO_FIRST_FLOOR 					 0
#define TUTORIAL_HARVEST 					 TUTORIAL_SLIDE_TO_FIRST_FLOOR + 1
#define TUTORIAL_AFTER_HARVEST 					 TUTORIAL_HARVEST + 1
#define TUTORIAL_PLANT 					 TUTORIAL_AFTER_HARVEST + 1
#define TUTORIAL_AFTER_PLANT 					 TUTORIAL_PLANT + 1
#define TUTORIAL_RECEIVE_PLANT_REWARD 					 TUTORIAL_AFTER_PLANT + 1
#define TUTORIAL_CATCH_BUG 					 TUTORIAL_RECEIVE_PLANT_REWARD + 1
#define TUTORIAL_AFTER_CATCH_BUG 					 TUTORIAL_CATCH_BUG + 1
#define TUTORIAL_OPEN_MACHINE 					 TUTORIAL_AFTER_CATCH_BUG + 1
#define TUTORIAL_SKIP_TIME_FREEZE_MACHINE 					 TUTORIAL_OPEN_MACHINE + 1
#define TUTORIAL_PRODUCT 					 TUTORIAL_SKIP_TIME_FREEZE_MACHINE + 1
#define TUTORIAL_SKIP_TIME 					 TUTORIAL_PRODUCT + 1
#define TUTORIAL_AFTER_SKIP_TIME 					 TUTORIAL_SKIP_TIME + 1
#define TUTORIAL_RECEIVE_ORDER 					 TUTORIAL_AFTER_SKIP_TIME + 1
#define TUTORIAL_DELIVERY_ORDER 					 TUTORIAL_RECEIVE_ORDER + 1
#define TUTORIAL_RECEIVE_ORDER_REWARD 					 TUTORIAL_DELIVERY_ORDER + 1
#define TUTORIAL_AFTER_RECEIVE_ORDER_REWARD 					 TUTORIAL_RECEIVE_ORDER_REWARD + 1
#define TUTORIAL_OPEN_NEW_FLOOR 					 TUTORIAL_AFTER_RECEIVE_ORDER_REWARD + 1
#define TUTORIAL_NPC_MACHINE_REPAIR 					 TUTORIAL_OPEN_NEW_FLOOR + 1
#define TUTORIAL_AFTER_NPC_MACHINE_REPAIR 					 TUTORIAL_NPC_MACHINE_REPAIR + 1
#define TUTORIAL_PUT_POT 					 TUTORIAL_AFTER_NPC_MACHINE_REPAIR + 1
#define TUTORIAL_BUY_POT 					 TUTORIAL_PUT_POT + 1
#define TUTORIAL_MOVE_POT 					 TUTORIAL_BUY_POT + 1
#define TUTORIAL_CONNECT_SNS 					 TUTORIAL_MOVE_POT + 1
#define TUTORIAL_PRIVATE_SHOP_GUIDE 					 TUTORIAL_CONNECT_SNS + 1
#define TUTORIAL_BUY_ITEM_PRIVATE_SHOP 					 TUTORIAL_PRIVATE_SHOP_GUIDE + 1
#define TUTORIAL_NEWSBOARD 					 TUTORIAL_BUY_ITEM_PRIVATE_SHOP + 1
#define TUTORIAL_UPGRADE_POT 					 TUTORIAL_NEWSBOARD + 1
#define TUTORIAL_MAX 					 TUTORIAL_UPGRADE_POT + 1


#define VERSION_ID 					 0
#define VERSION_PLATFORM 					 VERSION_ID + 1
#define VERSION_RESOLUTION 					 VERSION_PLATFORM + 1
#define VERSION_NUMBER 					 VERSION_RESOLUTION + 1
#define VERSION_LINK 					 VERSION_NUMBER + 1
#define VERSION_MAX 					 VERSION_LINK + 1

#define VERSION_WRONG_UPDATE 					 0
#define VERSION_HAS_NOT_UPDATE 					 VERSION_WRONG_UPDATE + 1
#define VERSION_HAS_UPDATE 					 VERSION_HAS_NOT_UPDATE + 1


#define CONSTANT_USER_LEVEL 					 0
#define CONSTANT_DO_PAID_UNLOCK 					 CONSTANT_USER_LEVEL + 1
#define CONSTANT_ORDER_CONTROL_ENOUGH 					 CONSTANT_DO_PAID_UNLOCK + 1
#define CONSTANT_ORDER_CONTROL_MISS 					 CONSTANT_ORDER_CONTROL_ENOUGH + 1
#define CONSTANT_ORDER_BUG_PEARL 					 CONSTANT_ORDER_CONTROL_MISS + 1
#define CONSTANT_ORDER_BUG_RATE 					 CONSTANT_ORDER_BUG_PEARL + 1
#define CONSTANT_MAX 					 CONSTANT_ORDER_BUG_RATE + 1


#define MAX_SLOT_PER_FLOOR 					 6
#define SLOT_TUTORIAL 					 6

#define STOCK_SILO 					 0
#define STOCK_BARN 					 STOCK_SILO + 1
#define STOCK_WAREHOUSE 					 STOCK_BARN + 1

#define MACHINE_LOCK 					 0
#define MACHINE_UNLOCK 					 MACHINE_LOCK + 1
#define MACHINE_READY 					 MACHINE_UNLOCK + 1

#define MACHINE_DURABILITY_ADD 					 20
#define MACHINE_SLOT_MAX 					 16
#define MACHINE_DEFAULT_STOCK_CAPACITY 					 13

#define MACHINE_STATUS_PROCESSING 					 1
#define MACHINE_STATUS_COMPLETED 					 MACHINE_STATUS_PROCESSING + 1

#define FLOOR_MAX 					 20
#define STOCK_MAX 					 3


#define ORDER_NORMAL 					 0
#define ORDER_DAILY 					 ORDER_NORMAL + 1
#define ORDER_EVENT 					 ORDER_DAILY + 1
#define ORDER_TYPE_MAX 					 ORDER_EVENT + 1

#define ORDER_DAILY_INDEX 					 4 // start from 0
#define ORDER_MAX 					 9

#define NEW_DAILY_ORDER_PAID_WAIT_TIME 					 3 * 60 // 3 minutes

#define USER_LEVEL_ORDER_CONTROL 					 10
#define USER_LEVEL_ORDER_BUG_PEARL 					 8

#define ORDER_LETTER_COUNT 					 6

#define NPC_SNOW_WHITE_ID 					 0 // follow client data
#define NPC_FROG_PRINCE_ID 					 2 // follow client data
#define NPC_TINKER_BELL_ID 					 3 // follow client data

#define ORDER_RANDOM_ITEM_FOLLOW_USER_STOCK 					 0
#define ORDER_RANDOM_ITEM 					 1
#define ORDER_RANDOM_BUG_AND_PEARL 					 2

#define MAX_FLOOR_ON_SCREEN 					 2

#define GOLD_ID 					 0
#define DIAMOND_ID 					 1
#define REPUTATION_ID 					 2
#define EXP_ID 					 3
#define EXP_GIFT 					 6

#define NPC_MAX 					 10

#define IT_GAMEITEM 					 -1
#define IT_POT 					 0
#define IT_PLANT 					 1
#define IT_BUILDING 					 2
#define IT_BUG 					 3
#define IT_PRODUCT 					 4
#define IT_MONEY 					 5
#define IT_COUNT 					 6
#define IT_DECOR 					 7
#define IT_MATERIAL 					 8
#define IT_CLOUD_FLOOR 					 12


#define PRIVATE_SHOP_MAX_SLOT 					 20
#define PRIVATE_SHOP_DEFAULT_SLOT_NUMBER 					 2
#define PRIVATE_SHOP_START_SLOT_FRIEND 					 2
#define PRIVATE_SHOP_NUMBER_OF_SLOT_FRIEND 					 4
#define PRIVATE_SHOP_START_SLOT_DIAMOND 					 6
#define PRIVATE_SHOP_ADS_PENDING_DURATION 					 30 // minutes
#define PRIVATE_SHOP_LOCK_EXPIRED_DURATION 					 12 // after 12 seconds, the lock (if any) will be automatically unlocked.
#define PRIVATE_SHOP_ADS_MAX_TIME 					 3 * 60 * 60 // 3 hours
#define PRIVATE_SHOP_ITEM_EXPIRE_TIME 					 24 * 60 * 60


#define NPC_SHOP_REFRESH_TIME 					 24 * 60 * 60 // once a day
#define NPC_SHOP_NUM_ITEM_SELL 					 6


#define MAGIC_WATER_BOTTLE_DROP_RATIO 					 10
#define MACHINE_REDUCE_GOLD_MAINTAIN_RATIO 					 10
#define MACHINE_DATA_LOCK_TIME 					 5


#define PS_ITEM_STATUS_EMPTY 					 0
#define PS_ITEM_STATUS_SELLING 					 1
#define PS_ITEM_STATUS_SOLD 					 2
#define PS_ITEM_EXPIRING 					 3
#define PS_ITEM_EXPIRED 					 4


#define NEWS_BOARD_MAX_SLOT 					 24
#define NEWS_BOARD_ADS_MAX_TIME 					 5 * 60 // 5 minutes
#define NEWS_BOARD_REFRESH_TIME 					 5 * 60 // 5 minutes


#define MAX_GIFT_DAILY_NUM 					 5


#define ACTION_HARVEST_PLANT 					 2
#define ACTION_HARVEST_PRODUCT 					 3
#define ACTION_REPAIR_FRIEND_MACHINE 					 4


#define PRODUCT_ID_BORUA 					 1 // bo rua
#define PRODUCT_ID_DOMDOM 					 4 // dom dom
#define PRODUCT_ID_OCSEN 					 9 // oc sen
#define PRODUCT_ID_NGOCDO 					 10 // ngoc do
#define PRODUCT_ID_NGOCVANG 					 11 // ngoc vang
#define PRODUCT_ID_NGOCXANHBIEN 					 12 // ngoc xanh bien
#define PRODUCT_ID_NGOCCAM 					 26 // ngoc cam
#define PRODUCT_ID_NGOCTIM 					 33 // ngoc tim
#define PRODUCT_ID_NGOCXANHLA 					 35 // ngoc xanh la
#define PRODUCT_ID_HATHUONGDUONG 					 18 // hat huong duong

#define MATERIAL_MAGIC_WATER_BOTTLE 					 9
#define MATERIAL_PROTECT_AMULET 					 MATERIAL_MAGIC_WATER_BOTTLE + 1
#define MATERIAL_LUCKY_LEAF_RED_SMALL 					 MATERIAL_PROTECT_AMULET + 1
#define MATERIAL_LUCKY_LEAF_RED_MEDIUM 					 MATERIAL_LUCKY_LEAF_RED_SMALL + 1
#define MATERIAL_LUCKY_LEAF_RED_LARGE 					 MATERIAL_LUCKY_LEAF_RED_MEDIUM + 1
#define MATERIAL_LUCKY_LEAF_PURPLE_SMALL 					 MATERIAL_LUCKY_LEAF_RED_LARGE + 1
#define MATERIAL_LUCKY_LEAF_PURPLE_MEDIUM 					 MATERIAL_LUCKY_LEAF_PURPLE_SMALL + 1
#define MATERIAL_LUCKY_LEAF_PURPLE_LARGE 					 MATERIAL_LUCKY_LEAF_PURPLE_MEDIUM + 1
#define MATERIAL_LUCKY_LEAF_YELLOW_SMALL 					 MATERIAL_LUCKY_LEAF_PURPLE_LARGE + 1
#define MATERIAL_LUCKY_LEAF_YELLOW_MEDIUM 					 MATERIAL_LUCKY_LEAF_YELLOW_SMALL + 1
#define MATERIAL_LUCKY_LEAF_YELLOW_LARGE 					 MATERIAL_LUCKY_LEAF_YELLOW_MEDIUM + 1
#define MATERIAL_LUCKY_LEAF_GREEN_SMALL 					 MATERIAL_LUCKY_LEAF_YELLOW_LARGE + 1
#define MATERIAL_LUCKY_LEAF_GREEN_MEDIUM 					 MATERIAL_LUCKY_LEAF_GREEN_SMALL + 1
#define MATERIAL_LUCKY_LEAF_GREEN_LARGE 					 MATERIAL_LUCKY_LEAF_GREEN_MEDIUM + 1
#define MATERIAL_LUCKY_LEAF_BLUE_SMALL 					 MATERIAL_LUCKY_LEAF_GREEN_LARGE + 1
#define MATERIAL_LUCKY_LEAF_BLUE_MEDIUM 					 MATERIAL_LUCKY_LEAF_BLUE_SMALL + 1
#define MATERIAL_LUCKY_LEAF_BLUE_LARGE 					 MATERIAL_LUCKY_LEAF_BLUE_MEDIUM + 1
#define MATERIAL_NET_ID 					 MATERIAL_LUCKY_LEAF_BLUE_LARGE + 1

